### PR TITLE
Set value later, when value is needed.

### LINKED ISSUE #242: Conflict with Automattic LiveBlog Plugin
### What did you expect to happen?

No conflict and fatal error while using the News SEO with the Automattic LiveBlog plugin.
### What happened instead?

The following fatal error appears while using the News SEO and [Automattic Liveblog plugin](https://wordpress.org/plugins/liveblog/).

```

Fatal error: Uncaught Error: Call to a member function get() on null in /wp-includes/query.php:28 Stack trace: #0 /wp-content/plugins/liveblog/liveblog.php(415): get_query_var('liveblog') #1 /wp-content/plugins/liveblog/liveblog.php(86): WPCOM_Liveblog::is_entries_ajax_request() #2 /wp-includes/plugin.php(601): WPCOM_Liveblog::add_custom_post_type_support(Object(WP_Query)) #3 /wp-includes/query.php(2493): do_action_ref_array('pre_get_posts', Array) #4 /wp-includes/query.php(4006): WP_Query->get_posts() #5 /wp-includes/query.php(4117): WP_Query->query(Array) #6 /wp-content/plugins/wpseo-news/classes/class-meta-box.php(194): WP_Query->__construct(Array) #7 /wp-content/plugins/wpseo-news/classes/class-meta-box.php(218): WPSEO_News_Meta_Box->standouts_used() #8 /wp-includes/query.php on line 28
```
### How can we reproduce this behavior?
1. Activate the News SEO plugin
2. Activate the Automattic LiveBlog plugin
3. Go to add a new post or page
### Technical info
- WordPress version: 4.5.3
- Yoast SEO version: 3.4.2
- News SEO version: 3.4
- LiveBlog version: 1.5

### LINKED ISSUE #243: PHP Warning While Using the bbPress
### What did you expect to happen?

No PHP warning on the news sitemap while using bbPress.
### What happened instead?

News sitemap shows the following PHP warning while using bbPress.

`Warning:  in_array() expects parameter 2 to be array, null given in /wp-content/plugins/bbpress/includes/common/functions.php on line 1446`
### How can we reproduce this behavior?
- Go to the news sitemap and view the source code
### Technical info
- WordPress version: 4.6
- Yoast SEO version: 3.4.2
- News SEO version: 3.4

### LINKED ISSUE #262: Edit Post Screen creates PHP Fatal error when Piklist plugin is active
### What did you expect to happen?
To be able to edit the post screen
### What happened instead?
I was unable to
### How can we reproduce this behavior?
**1.Create a post**

**2.Put Yoast SEO (free or paid) on site**

**3.Activate Piklist**

**4.See errors**

PHP message: PHP Fatal error: Call to a member function get() on null

screen shot 2016-12-06 at 2 52 23 pm

Stack Trace provided by user

2016/12/06 18:49:50 [error] 11#11: *64 FastCGI sent in stderr: "PHP message: PHP Fatal error: Call to a member function get() on null in /var/www/web/wp/wp-includes/query.php on line 28
PHP message: PHP Stack trace:
PHP message: PHP 1. {main}() /var/www/web/wp/wp-admin/post-new.php:0
PHP message: PHP 2. require_once() /var/www/web/wp/wp-admin/post-new.php:10
PHP message: PHP 3. require_once() /var/www/web/wp/wp-admin/admin.php:31
PHP message: PHP 4. require_once() /var/www/web/wp/wp-load.php:44
PHP message: PHP 5. require_once() /var/www/web/wp-config.php:9
PHP message: PHP 6. do_action() /var/www/web/wp/wp-settings.php:295
PHP message: PHP 7. call_user_func_array:{/var/www/web/wp/wp-includes/plugin.php:524}() /var/www/web/wp/wp-includes/plugin.php:524
PHP message: PHP 8. wpseo_init() /var/www/web/wp/wp-includes/plugin.php:524
PHP message: PHP 9. WPSEO_Meta::init() /var/www/web/app/plugins/wordpress-seo/wp-seo-main.php:250
PHP message: PHP 10. apply_filters() /var/www/web/app/plugins/wordpress-seo/inc/class-wpseo-meta.php:291
PHP message: PHP 11. call_user_func_array:{/var/www/web/wp/wp-includes/plugin.php:235}() /var/www/web/wp/wp-includes/plugin.php:235
PHP message: PHP 12. WPSEO_News_Meta_Box->add_meta_fields_to_wpseo_meta() /var/www/web/wp/wp-includes/plugin.php:235
PHP message: PHP 13. WPSEO_News_Meta_Box->get_meta_boxes() /var/www/web/app/plugins/yoast-news-seo/classes/class-meta-box.php:129
PHP message: PHP 14. WPSEO_News_Meta_Box->standout_description() /var/www/web/app/plugins/yoast-news-seo/classes/class-meta-box.php:77
PHP message: PHP 15. WPSEO_News_Meta_Box->standouts_used() /var/www/web/app/plugins/yoast-news-seo/classes/class-meta-box.php:224
PHP message: PHP 16. WP_Query->__construct() /var/www/web/app/plugins/yoast-news-seo/classes/class-meta-box.php:212
PHP message: PHP 17. WP_Query->query() /var/www/web/wp/wp-includes/query.php:4161
PHP message: PHP 18. WP_Query->get_posts() /var/www/web/wp/wp-includes/query.php:4050
PHP message: PHP 19. apply_filters_ref_array() /

Can you provide a link to a page which shows this issue?

### Technical info
* WordPress version: 4.6.1
* Yoast SEO version: 3.9
* News SEO: 3.9
* Piklist: 0.9.9.9  (may also be seen as [PIKLIST | Rapid development framework](https://wordpress.org/plugins/piklist/) )

### PR DESCRIPTION
**Pull request by andizer**
## Summary

This PR can be summarized in the following changelog entry:
* [Bug][Compatibility] Fixes a incompatibility bug for Piklist, bbPress andLiveblog (Automattic)

## Relevant technical choices:

* The `WP_Query` was executed too early, so set the value that relies on it later.

## Test instructions

This PR can be tested by following these steps:
* The pull fixes some errors with the PikList #262, Liveblog #242 and bbPress #243 plugins
* Follow each step below for each plugin
* Checkout `trunk`
* Follow the steps to reproduce the issue in the mentioned issues
* Checkout this branch
* Follow the steps again and see it being solved

Fixes #262
Fixes #242
Fixes #243

### CODE REVIEW

File: classes/class-meta-box.php [hunk 1]
```diff
@@ -154,7 +154,11 @@ public function header() {
 	public function content() {
 		// Build tab content
 		$content = '';
-		foreach ( $this->get_meta_boxes() as $meta_key => $meta_box ) {
+
+		$metaboxes = $this->get_meta_boxes();
+		$metaboxes['newssitemap-standout']['description'] = $this->standout_description();
```
Comment (moorscode) [inline classes/class-meta-box.php]: We should implement this in a more generic manner.
If we pass the `$meta_key` and `$meta_box` to a function (inside the `foreach` loop) which can inject the data needed, that would separate the concerns better.

**Comment by CarolineGeven** [comment]
CR and acceptance 👍
